/* soapSDEService.h
   Generated by gSOAP 2.8.33 for SDE.h

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapSDEService_H
#define soapSDEService_H
#include "soapH.h"
#include "SQLClient.h"

    class SOAP_CMAC SDEService : public soap {
      public:
        /// Variables globally declared in SDE.h, if any
        /// Construct a service with new managing context
        SDEService(SQLClient* _sql);
        /// Copy constructor
        SDEService(const SDEService&);
        /// Construct service given a managing context
        SDEService(const struct soap&);
        /// Constructor taking input+output mode flags for the new managing context
        SDEService(soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        SDEService(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and managing context
        virtual ~SDEService();
        /// Delete all deserialized data (with soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to defaults
        virtual void reset();
        /// Initializer used by constructors
        virtual void SDEService_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual SDEService *copy() SOAP_PURE_VIRTUAL;
        /// Copy assignment
        SDEService& operator=(const SDEService&);
        /// Close connection (normally automatic)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Return sender-related fault to sender
        virtual int soap_senderfault(const char *string, const char *detailXML);
        /// Return sender-related fault with SOAP 1.2 subcode to sender
        virtual int soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML);
        /// Return receiver-related fault to sender
        virtual int soap_receiverfault(const char *string, const char *detailXML);
        /// Return receiver-related fault with SOAP 1.2 subcode to sender
        virtual int soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML);
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Run simple single-thread (iterative, non-SSL) service on port until a connection error occurs (returns SOAP_OK or error code), use this->bind_flag = SO_REUSEADDR to rebind for immediate rerun
        virtual int run(int port);
    #if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
        /// Run simple single-thread SSL service on port until a connection error occurs (returns SOAP_OK or error code), use this->bind_flag = SO_REUSEADDR to rebind for immediate rerun
        virtual int ssl_run(int port);
    #endif
        /// Bind service to port (returns master socket or SOAP_INVALID_SOCKET)
        virtual SOAP_SOCKET bind(const char *host, int port, int backlog);
        /// Accept next request (returns socket or SOAP_INVALID_SOCKET)
        virtual SOAP_SOCKET accept();
    #if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
        /// When SSL is used, after accept() should perform and accept SSL handshake
        virtual int ssl_accept();
    #endif
        /// After accept() serve this request (returns SOAP_OK or error code)
        virtual int serve();
        /// Used by serve() to dispatch a request (returns SOAP_OK or error code)
        virtual int dispatch();
        ///
        /// Service operations are listed below (you should define these)
        /// Note: compile with -DWITH_PURE_VIRTUAL for pure virtual methods
        ///
        /// Web service operation 'getLoginInfo' (returns SOAP_OK or error code)
        virtual int getLoginInfo(SDEKey *session, std::string *desiredOnyen, std::string &response) SOAP_PURE_VIRTUAL;
        /// Web service operation 'getRegisteredClasses' (returns SOAP_OK or error code)
        virtual int getRegisteredClasses(SDEKey *session, std::string *desiredOnyen, std::vector<std::string> &response) SOAP_PURE_VIRTUAL;
        /// Web service operation 'addOnyen' (returns SOAP_OK or error code)
        virtual int addOnyen(SDEKey *session, std::string *desiredOnyen, std::string *desiredPassword, std::string &response) SOAP_PURE_VIRTUAL;
        /// Web service operation 'registerClass' (returns SOAP_OK or error code)
        virtual int registerClass(SDEKey *session, std::string *desiredOnyen, std::string *desiredClass, std::string &response) SOAP_PURE_VIRTUAL;
    private:
        SQLClient* sql;
    };
#endif
